# Generated by Django 4.2.2 on 2023-06-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='added_by',
            new_name='user',
        ),
    ]
